version: '3.8'
services:
    api:
      depends_on:
        - db
    # Postgres
    db:
      container_name: ${APP_NAME}_postgres
      image: ${POSTGRES_VERSION}
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - ALLOW_IP_RANGE=0.0.0.0/0
      deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - node.labels.${APP_NAME}.db-data == true
      healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
            timeout: 45s
            interval: 10s
            retries: 10
