version: '3.8'

x-vars: &nestjs-vars
  NODE_VERSION: ${NODE_VERSION}
  ENV: ${ENV}
  NODE_ENV: ${NODE_ENV}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_HOST: ${POSTGRES_HOST}
  SERVER_HOST: ${SERVER_HOST:-0.0.0.0}
  SERVER_PORT: ${SERVER_PORT:-3000}
  PORT: ${PORT:-3000}
  APP_NAME: ${APP_NAME}
  APP_DESCRIPTION: ${APP_DESCRIPTION}
  HEALTHCHECK_ENDPOINT: ${HEALTHCHECK_ENDPOINT}
  APP_YARN_CMD: ${APP_YARN_CMD}
  APP_CMD: ${APP_CMD}
  MIGRATIONS: ${MIGRATIONS}
  MIGRATE_DROP: ${MIGRATE_DROP:-false}
  MIGRATIONS_WITH_TYPEORM: ${MIGRATIONS_WITH_TYPEORM:-false}
  MINIO_ENDPOINT: ${MINIO_ENDPOINT}
  MINIO_PORT: ${MINIO_PORT}
  MINIO_KEY: ${MINIO_KEY}
  MINIO_SECRET: ${MINIO_SECRET}
  MINIO_BUCKET: ${MINIO_BUCKET}
  MINIO_USE_SSL: ${MINIO_USE_SSL}
  SGPD_BYPASS: ${SGPD_BYPASS:-false}
  ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
  ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
  SWAGGER_USER: ${SWAGGER_USER}
  SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: ${SMTP_PORT}
  SMTP_USERNAME: ${SMTP_USERNAME}
  SMTP_PASSWORD: ${SMTP_PASSWORD}
  FRONT_DOMAIN: ${FRONT_DOMAIN}
  MIGRATIONS_ORM: ${MIGRATIONS_ORM}
  TIMEZONE: ${TIMEZONE}
  FRONTEND_URL: ${FRONTEND_URL}
  ENDPOINT_CACHE_TLS: ${ENDPOINT_CACHE_TLS}
  ENDPOINT_CACHE_MAX_REQUESTS: ${ENDPOINT_CACHE_MAX_REQUESTS}
  POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
  POSTGRES_SYNCHRONIZE: ${POSTGRES_SYNCHRONIZE}
  POSTGRES_DEBUG: ${POSTGRES_DEBUG}
  POSTGRES_METADATA_CACHE: ${POSTGRES_METADATA_CACHE}
  JWT_PUB: ${JWT_PUB}
  JWT_SECRET: ${JWT_SECRET}
  JWT_EXPIRE_TIME: ${JWT_EXPIRE_TIME:-24h}
  JWT_NEVER_EXPIRES: ${JWT_NEVER_EXPIRES:-false}
  JWT_ISSUER: ${JWT_ISSUER}
  COOKIE_ENABLED: ${COOKIE_ENABLED}
  MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-noreply@decea.gov.br}
  MAIL_FROM_NAME: ${MAIL_FROM_NAME:-DECEA}
  MAIL_IGNORETLS: ${MAIL_IGNORETLS:-true}
  MAIL_SECURE: ${MAIL_SECURE:-false}
  PUBLICATIONS_PUBLISHED_ENDPOINT: ${PUBLICATIONS_PUBLISHED_ENDPOINT}
  PUBLICATIONS_REVOKED_ENDPOINT: ${PUBLICATIONS_REVOKED_ENDPOINT}
  PNPM: ${PNPM:-false}
  PNPM_VERSION: ${PNPM_VERSION:-7.24.3}
  LOCKFILE: ${LOCKFILE:-yarn.lock}
  NODE_FRAMEWORK: ${NODE_FRAMEWORK:-nestjs}
  ALLOWED_DOMAINS: ${ALLOWED_DOMAINS}
  JWT_EVENTOS: ${JWT_EVENTOS}
  EXTERNAL_URL_LPNA_LOGIN: ${EXTERNAL_URL_LPNA_LOGIN}
  EXTERNAL_URL_EVENTOS_DECEA: ${EXTERNAL_URL_EVENTOS_DECEA}
  EXTERNAL_URL_ICEIA: ${EXTERNAL_URL_ICEIA}
  EXTERNAL_URL_AVATAR_OPERADOR: ${EXTERNAL_URL_AVATAR_OPERADOR}
  EXTERNAL_URL_PUBLICACAO: ${EXTERNAL_URL_PUBLICACAO}
  NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED}

services:
  migrations:
    container_name: ${APP_NAME}_migrations
    build:
      context: ../
      dockerfile: docker-nestjs-environment/Dockerfile
      target: migrations
      args:
        << : *nestjs-vars

    image: "${CI_REGISTRY_IMAGE:-local}/${APP_NAME}-migrations:${CI_COMMIT_SHORT_SHA:-local}"
    depends_on:
      - db
    environment:
      << : *nestjs-vars
    deploy:
      replicas: 1
      restart_policy:
          condition: on-failure
    working_dir: /app
    command: sh docker-nestjs-environment/migrations-${MIGRATIONS_ORM:-mikro-orm}
    # command: sh -c "tail -f /dev/null"