version: '3.8'

services:

  api:
    
    build:
      context: ../
      dockerfile: docker-nestjs-environment/Dockerfile
      target: runner
    deploy:
      replicas: ${REPLICAS}
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: ${UPDATE_PARALLELISM:-1}
        delay: 10s
      restart_policy:
        condition: on-failure
