version: '3.8'

services:

  minio:
    container_name: ${APP_NAME}_minio
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    volumes:
      - ./minio-data:/nas
    ports:
      - "${MINIO_PORT:-9000}:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
    deploy:
      mode: replicated                                                                                                                                     
      update_config:                                                                                                                                       
        parallelism: 1                                                                                                                                   
        delay: 10s                                                                                                                                       
        failure_action: rollback
        order: start-first                                                                                                                               
      restart_policy:                                                                                                                                      
        condition: on-failure
    command: gateway nas /nas
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 20s
      retries: 3

volumes:
  minio-data:

